
networks:
  monitoring:
    name: core-prod-monitoring_internal
    driver: bridge
    attachable: true

  traefik_backbone:
    name: traefik_backbone
    external: true

services:
  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml:ro
      - $persist_data_home/loki:/loki
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 -O- http://localhost:3100/ready | grep -q 'ready'"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - ./config/promtail.yaml:/etc/promtail/config.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring
    depends_on:
      loki:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL
      - GF_AUTH_GENERIC_OAUTH_ENABLED
      - GF_AUTH_GENERIC_OAUTH_NAME
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      - GF_AUTH_GENERIC_OAUTH_SCOPES
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL
      - GF_AUTH_GENERIC_OAUTH_API_URL
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
      - GF_AUTH_SIGNOUT_REDIRECT_URL
      - GF_AUTH_OAUTH_AUTO_LOGIN
    volumes:
      - $persist_data_home/grafana:/var/lib/grafana
      - ./config/datasources:/etc/grafana/provisioning:ro
    networks:
      - monitoring
      - traefik_backbone
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.stickpile.net`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=httpsResolve"
      - "traefik.http.routers.grafana.middlewares=middlewares-geoipfilter"

    depends_on:
      loki:
        condition: service_healthy
