name: traefik
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: core_services/traefik
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: blocky-tailscale
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: network-services/blocky-tailscale
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: monitoring
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: core_services/monitoring
compose_files:
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: authentik
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: core_services/authentik
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: media_server
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: web-apps/jellyfin
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: seafile
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: web-apps/seafile
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
