# name: moose
# repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
# reference: prod
# working_dir: core_services/moose
# compose_files: 
#   - compose.yaml
# env_files:
#   - remote:secrets.enc.env
# ---
name: traefik
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: core_services/traefik
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: tailscale-support
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: other_services/tailscale-support
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: authentik
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: core_services/authentik
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: media_server
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: web-apps/jellyfin
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: seafile
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: web-apps/seafile
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
# ---
# name: meshing-around
# repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
# reference: prod
# working_dir: web-apps/seafile
# compose_files: 
#   - compose.yaml
# env_files:
#   - remote:secrets.enc.env
---
name: affine
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: web-apps/affine
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: linkstack
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: web-apps/linkstack
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: kiwix
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: web-apps/kiwix
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
# ---
# name: pbx
# repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
# reference: prod
# working_dir: other-apps/asterisk-pbx
# compose_files: 
#   - compose.yaml
# env_files:
#   - remote:secrets.enc.env
