# name: grafana
# repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
# reference: prod
# working_dir: core_services/traefik
# compose_files: 
#   - compose.yaml
# env_files:
#   - remote:secrets.enc.env
# ---
name: traefik
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: compose/traefik
compose_files:
  - compose.yaml
env_files:
  - remote:../../shared/nfs.enc.env
  - remote:secrets.enc.env
---
name: authentik
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: compose/authentik
compose_files:
  - compose.yaml
env_files:
  - remote:../../shared/nfs.enc.env
  - remote:secrets.enc.env
---
name: blocky
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: compose/blocky
compose_files:
  - compose.yaml
env_files:
  - remote:../../shared/nfs.enc.env
  - remote:secrets.enc.env
---
name: media_server
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: compose/media-server
compose_files:
  - compose.yaml
env_files:
  - remote:../../shared/nfs.enc.env
  - remote:secrets.enc.env
# ---
# name: seafile
# repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
# reference: prod
# working_dir: web-apps/seafile
# compose_files:
#   - compose.yaml
# env_files:
#   - remote:../../shared/nfs.enc.env
#   - remote:secrets.enc.env

