# name: moose
# repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
# reference: prod
# working_dir: core_services/moose
# compose_files: 
#   - compose.yaml
# env_files:
#   - remote:secrets.enc.env
# ---
name: traefik
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: core_services/traefik
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
