# name: moose
# repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
# reference: prod
# working_dir: core_services/moose
# compose_files: 
#   - compose.yaml
# env_files:
#   - remote:secrets.enc.env
# ---
name: traefik
destroy: true
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: core_services/traefik
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: authentik
destroy: true
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: core_services/authentik
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: media_server
destroy: true
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: web-apps/jellyfin
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: seafile
destroy: true
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: web-apps/seafile
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
# ---
# name: meshing-around
# repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
# reference: prod
# working_dir: web-apps/seafile
# compose_files: 
#   - compose.yaml
# env_files:
#   - remote:secrets.enc.env
---
name: affine
destroy: true
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: web-apps/affine
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
---
name: kiwix
destroy: true
repository_url: https://github.com/pcs3rd/stickpile_compose-config.git
reference: prod
working_dir: web-apps/kiwix
compose_files: 
  - compose.yaml
env_files:
  - remote:secrets.enc.env
