version: "3.7"
services:

  static-file-server:
    volumes:
      - $persist_data_home/mtd/downloads:/downloads
    env_file:  
      - secrets.enc.env  
    image: halverneus/static-file-server:latest
    labels:                                                                              # Optional if accessing directly via port
      - "traefik.enable=true"                                                            # Enable/Disable Traefik
      - "traefik.http.routers.servMapTilesDownloader.rule=Host(`cache.mtd.stickpile.net`)"             # Access domain
      - "traefik.http.routers.servMapTilesDownloader.entrypoints=websecure"                  # Use HTTPS
      - "traefik.http.routers.servMapTilesDownloader.tls.certresolver=httpsResolve"          # HTTPS Cert Resolver
      - "traefik.http.services.servMapTilesDownloader.loadbalancer.server.port=8080"         # Container Port
#      - "traefik.http.routers.MapTilesDownloader.middlewares=middlewares-authentik@file" # If you're using authentik 
    networks: 
      traefik_backbone:

  MapTileDownloader:
    image: ghcr.io/pcs3rd/map-tile-downloader:main
    environment:
      - IS_DEBUG
      - HOST
      - IGNORE_DEV_WARNING
    volumes:
      - $persist_data_home/mtd/config:/config
      - $persist_data_home/mtd/downloads:/downloads
      - $persist_data_home/mtd/tile-cache:/tile-cache
    labels:                                                                              # Optional if accessing directly via port
      - "traefik.enable=true"                                                            # Enable/Disable Traefik
      - "traefik.http.routers.MapTilesDownloader.rule=Host(`mtd.stickpile.net`)"             # Access domain
      - "traefik.http.routers.MapTilesDownloader.entrypoints=websecure"                  # Use HTTPS
      - "traefik.http.routers.MapTilesDownloader.tls.certresolver=httpsResolve"          # HTTPS Cert Resolver
      - "traefik.http.services.MapTilesDownloader.loadbalancer.server.port=5000"         # Container Port
      - "traefik.http.routers.MapTilesDownloader.middlewares=middlewares-authentik@file" # If you're using authentik
    networks: 
      traefik_backbone:

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/New_York
    networks:
      - mesh-internal
      - traefik_backbone
    volumes:
      - $persist_data_home/node-red:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`red.stickpile.net`)"
      - "traefik.http.routers.node.entrypoints=websecure"
      - "traefik.http.routers.node.service=node"
      - "traefik.http.routers.node.tls.certresolver=httpsResolve"
      - "traefik.http.services.node.loadbalancer.server.port=1880"
      - "traefik.http.routers.node.middlewares=middlewares-authentik@file"
  meshing-around:
    stdin_open: true
    tty: true
    #devices:
    #  - /dev/ttyUSB0
    volumes:
      - $persist_data_home/meshing-around/config.ini:/app/config.ini:rw
      - $persist_data_home/meshing-around/data:/app/data
    image: ghcr.io/pcs3rd/meshing-around:dev
    networks:
      mesh-internal:
  meshtasticd:
    volumes:
#      - ${persist_data_home}/meshtasticd.yaml:/etc/meshtasticd/config.yaml:rw
      - $persist_data_home/meshtasticd-data:/var/
      - $persist_data_home/meshtasticd-data-store:/etc/meshtasticd
      - $persist_data_home/meshtasticd/db:/root/.portduino/default/prefs/
    ports:
      - 4403:4403
    restart: unless-stopped
    container_name: meshtasticd
    image: meshtastic/meshtasticd:beta
    networks:
      mesh-internal:

  # ollama:
  #   ports:
  #     - 11434:11434
  #   volumes:
  #     - /home/manager/scratchpad/ollama:/root/.ollama
  #   container_name: ollama
  #   image: alpine/ollama
  #   networks:
  #     internal:
  #   devices:
  #     - nvidia.com/gpu=all

networks:
  mesh-internal:
    name: web-prod-meshtastic_Internal
    driver: bridge
    attachable: true
  traefik_backbone: # For external containers.
    name: traefik_backbone
    external: true
