services:
  hugo:
    image: hugomods/hugo:exts-non-root
    command: server --bind 0.0.0.0
    user: 1000:1000
    volumes:
      - hugo_data:/src
    working_dir: /src
    depends_on:
      - webhook
    environment:
      - HUGO_ENVIRONMENT
      - HUGO_THEME
    networks:
      - traefik_backbone
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hugo.rule=Host(`pcs3rd.me`)"
      - "traefik.http.routers.hugo.entrypoints=websecure"
      - "traefik.http.routers.hugo.tls.certresolver=httpsResolve"
      - "traefik.http.services.hugo.loadbalancer.server.port=1313"
      - "traefik.http.routers.hugo.middlewares=bouncer@file"
      
  webhook:
    build: ./webhook
    command: -hooks /hooks/hooks.json -verbose -template -port 9000
    volumes:
      - hugo_data:/src
      - ./webhook:/hooks
    working_dir: /src
    environment:
      - WEBHOOK_SECRET
      - GIT_REPO_URL
    networks:
      - traefik_backbone
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hugowh.rule=Host(`update.pcs3rd.me`)"
      - "traefik.http.routers.hugowh.entrypoints=websecure"
      - "traefik.http.routers.hugowh.tls.certresolver=httpsResolve"
      - "traefik.http.services.hugowh.loadbalancer.server.port=9000"
      - "traefik.http.routers.hugowh.middlewares=bouncer@file"
volumes:
  hugo_data:
    name: hugo_data

networks:
  traefik_backbone: # For external containers.
    name: traefik_backbone
    external: true
