services:
  blocky:
    image: spx01/blocky

    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host

      - target: 53
        published: 53
        protocol: tcp
        mode: host

    environment:
      - TZ

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/app/config.yml:ro
      - ./config/lists:/userlists
      - qlogs:/querylog

    networks:
      - internal

    depends_on:
      - redis

    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s