services:
  blocky:
    image: spx01/blocky
    restart: on-failure

    ports:
      - target: 53
        published: 53
        protocol: udp

      - target: 53
        published: 53
        protocol: tcp

    environment:
      - TZ

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/app/config.yml:ro
      - ./config/lists:/userlists
      - qlogs:/querylog

    networks:
      - internal

    depends_on:
      - redis
