

services:
  cowrie:
    ports:
      - 22:22
      - 23:23
    image: cowrie/cowrie:latest
    networks: 
      - traefik_backbone
    

networks:
  traefik_backbone: # For external containers.
    name: traefik_backbone
    external: true
