services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:10.0.160
    environment:
      - PUID
      - PGID
      - TZ
      - MONGO_USER
      - MONGO_PASS
      - MONGO_HOST
      - MONGO_PORT
      - MONGO_DBNAME
      - MONGO_AUTHSOURCE
      - MEM_LIMIT
      - MEM_STARTUP
    env_file:  
      - secrets.enc.env  
    volumes:
      - $persist_data_home/unifi-network-application:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: on-failure

  mongo:
    image: docker.io/mongo:8.2.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_USER
      - MONGO_PASS
      - MONGO_DBNAME
      - MONGO_AUTHSOURCE
    env_file:  
      - secrets.enc.env  
    volumes: 
      - $persist_data_home/unifi-network-mongodb:/data/db
      #- ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:  
      - secrets.enc.env  
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_URL
      - ME_CONFIG_BASICAUTH
