
services:
  traefik:
    image: "traefik:v3.5.3"
    env_file:  
      - secrets.enc.env  
    command:
      #- "--log.level=DEBUG"
      - "-tracing=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.smtps.address=:465"
      - "--entryPoints.smtp.address=:587"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.mqtt.address=:8883"
      - "--entrypoints.ldaps.address=:636"
      # - "--entrypoints.websocket.address=:9001"
      - "--providers.docker.network=traefik_backbone"
      - "--providers.docker.network=traefik_backbone" #This is some dumb crap
      - "--certificatesresolvers.httpsResolve.acme.httpchallenge=true"
      - "--certificatesresolvers.httpsResolve.acme.httpchallenge.entrypoint=web"
      - "--accesslog=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.httpsResolve.acme.email=rdean@stickpile.net"
      - "--certificatesresolvers.httpsResolve.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.directory=/rules" 
      - "--log.level=INFO"
      - "--log.filePath=/var/log/traefik/access.log"
      - "--log.maxSize=500MB"
      - "--log.maxAge=12"
      - "--log.format=json"
      - "--experimental.plugins.crowdsec-bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.crowdsec-bouncer.version=v1.2.1"
      ## As a note, need to bring $BOUNCER-API-KEY into SOPS on every deployment
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8883:8883"
      - "8884:8884"
      - "4883:4883"
      - "888:888"
      - "636:636"
      - "442:442"
      - "465:465"
      - "587:587"
#      - "4318:4318"
    volumes:
      - $persist_data_home/letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      #- $persist_data_home/traefik-log:/var/log/traefik
      - ./rules:/rules
      - proxy-logs:/var/log/traefik
    networks: 
      - traefik_backbone
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`npm.stickpile.net`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=httpsResolve"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.middlewares=middlewares-authentik@file"
      - "traefik.http.middlewares.bouncer.plugin.crowdsec-bouncer.enabled=true"
      - "traefik.http.middlewares.bouncer.plugin.crowdsec-bouncer.crowdseclapikey=$BOUNCER-API-KEY"
    # healthcheck:
    #   test: ["CMD", "traefik", "healthcheck", "--ping"]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 5s

  crowdsec:
      image: crowdsecurity/crowdsec:v1.7.4-debian
      environment:
        PGID: "1000"
        COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve firix/authentik"
        PARSERS: "crowdsecurity/docker-logs"
        BOUNCER_KEY_TRAEFIK: $BOUNCER-API-KEY
      # expose:
      #   - "8080"
      volumes:
        - proxy-logs:/var/log/traefik:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - $persist_data_home/crowdsec/log:/var/log/crowdsec:ro
        - $persist_data_home/crowdsec/db:/var/lib/crowdsec/data
        - $persist_data_home/crowdsec/auth.log:/var/log/auth.log:ro
        - $persist_data_home/crowdsec/config:/etc/crowdsec
        #- $persist_data_home/traefik-log:/var/log/traefik:ro
      restart: unless-stopped
      labels:
        - "traefik.enable=false"
        - "traefik.http.routers.cs.rule=Host(`npm.crowdsec.stickpile.net`)"
        - "traefik.http.routers.cs.entrypoints=websecure"
        - "traefik.http.routers.cs.tls.certresolver=httpsResolve"
        - "traefik.http.services.cs.loadbalancer.server.port=8080"
        - "traefik.http.routers.cs.middlewares=middlewares-authentik@file"
        ## Middleware configuration
      networks:
        - traefik_backbone

  otel-collector:
    image: otel/opentelemetry-collector-contrib
#    volumes:
#      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
     # - 8888:8888 # Prometheus metrics exposed by the Collector
     # - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
      
networks:
  traefik_backbone: # For external containers.
    name: traefik_backbone
    external: true


volumes:
  proxy-logs: