
services:
  traefik:
    image: "traefik:v3.5.3"
    # env_file:  
    #   - secrets.enc.env  
    environment:
      - BOUNCER_API_KEY
    entrypoint: ["/bin/sh", "/etc/traefik/entrypoint.sh"]
    command:
      #- "--log.level=DEBUG"
      - "-tracing=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.p2p.address=:50300"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--providers.docker.network=traefik_backbone"
      - "--providers.docker.network=traefik_backbone" #This is some dumb crap
      - "--certificatesresolvers.httpsResolve.acme.httpchallenge=true"
      - "--certificatesresolvers.httpsResolve.acme.httpchallenge.entrypoint=web"
      - "--accesslog=true"
      - "--accesslog.format=json"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.httpsResolve.acme.email=rdean@stickpile.net"
      - "--certificatesresolvers.httpsResolve.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.directory=/rules" 
      - "--log.level=INFO"
      - "--log.filePath=/var/log/traefik/access.log"
      - "--log.maxSize=500"
      - "--log.maxAge=12"
      - "--log.format=json"
      - "--experimental.plugins.crowdsec-bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.crowdsec-bouncer.version=v1.2.1"
      ## As a note, need to bring BOUNCER-API-KEY into SOPS on every deployment
    ports:
      - "80:80"
      - "443:443"
      - "50300:50300"
    volumes:
      - ./entrypoint.sh:/etc/traefik/entrypoint.sh:ro   # ← mount the script
      - $persist_data_home/letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./rules:/rules
      - proxy-logs:/var/log/traefik
      - /run/secrets:/run/secrets
    tmpfs:
      - /run/secrets
    networks: 
      - traefik_backbone
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`npm.stickpile.net`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=httpsResolve"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.middlewares=middlewares-authentik@file"
      - "traefik.http.middlewares.bouncer.plugin.crowdsec-bouncer.enabled=true"
      - "traefik.http.middlewares.bouncer.plugin.crowdsec-bouncer.crowdseclapikey=$BOUNCER-API-KEY"
    # healthcheck:
    #   test: ["CMD", "traefik", "healthcheck", "--ping"]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 5s

  crowdsec:
      image: crowdsecurity/crowdsec:v1.7.4-debian
      environment:
        - PGID
        - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve firix/authentik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
        - PARSERS=crowdsecurity/docker-logs
        - BOUNCER_KEY_TRAEFIK
      # expose:
      #   - "8080"
      volumes:
        - proxy-logs:/var/log/traefik:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - $persist_data_home/crowdsec/log:/var/log/crowdsec:ro
        - $persist_data_home/crowdsec/db:/var/lib/crowdsec/data
        - $persist_data_home/crowdsec/auth.log:/var/log/auth.log:ro
        - $persist_data_home/crowdsec/config:/etc/crowdsec
        #- $persist_data_home/traefik-log:/var/log/traefik:ro
      restart: unless-stopped
      labels:
        - "traefik.enable=false"
        - "traefik.http.routers.cs.rule=Host(`npm.crowdsec.stickpile.net`)"
        - "traefik.http.routers.cs.entrypoints=websecure"
        - "traefik.http.routers.cs.tls.certresolver=httpsResolve"
        - "traefik.http.services.cs.loadbalancer.server.port=8080"
        - "traefik.http.routers.cs.middlewares=middlewares-authentik@file"
        ## Middleware configuration
      networks:
        - traefik_backbone
      
networks:
  traefik_backbone: # For external containers.
    name: traefik_backbone
    external: true


volumes:
  proxy-logs:

