http:
  routers:
    tar1090:
      entryPoints:
        - web
      rule: "(Host(`flights.stickpile.net`) && PathPrefix(`/tar1090`))"
      service: tar1090
      tls:
        certResolver: "httpsResolve"
  services:
    tar1090:
      loadBalancer:
        servers:
          - url: "http://100.96.14.67:80/tar1090"
        passHostHeader: false