services:
# BLOCKY - GO Based DNS Server with CLI Support
 
  blocky:
    image: spx01/blocky
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ
    volumes:
      # Optional to synchronize the log timestamp with host
      - /etc/localtime:/etc/localtime:ro
      # config file
      - ./config/config.yml:/app/config.yml:ro
      - ./config/lists:/userlists
      - qlogs:/querylog
    depends_on:
      - redis

  blocky-redis: 
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - $persist_data_home/blocky-redis-state:/data

  blocky-ui:
      image: ghcr.io/gabeduartem/blocky-ui:latest # or for example `blocky-ui:1.5.0` if you prefer pinned versions
      restart: unless-stopped
      depends_on:
        - blocky
      ports:
        - 3000:3000
      volumes:
        - qlogs:/querylog
      environment:
        - BLOCKY_API_URL
        - QUERY_LOG_TYPE
        - QUERY_LOG_TARGET
        - INSTANCE_NAME