services:
# BLOCKY - GO Based DNS Server with CLI Support
  blocky:
    image: spx01/blocky:v0.28.2
    restart: on-failure
    # Optional the instance hostname for logging purpose
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ
    env_file:  
      - secrets.enc.env  
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # config file
      # - ./config.yml:/app/config.yml
      - $persist_data_home/blocky-state/config.yml:/app/config.yml
      - $persist_data_home/blocky-lists/:/userlists
  blocky-redis: 
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - $persist_data_home/blocky-redis-state:/data
  blocky-frontend:
    environment; configs:
      - API_URL="http://192.168.1.10:4000"
    depends_on:
      - blocky
    image: ghcr.io/mozart409/blocky-frontend:latest
    ports:
      - '8002:8002'