services:
# BLOCKY - GO Based DNS Server with CLI Support
  blocky:
    image: spx01/blocky
    restart: on-failure
    # Optional the instance hostname for logging purpose
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ
    env_file:  
      - secrets.enc.env  
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # config file
      # - ./config.yml:/app/config.yml
      - $persist_data_home/blocky-state/config.yml:/app/config.yml
      - $persist_data_home/blocky-lists/:/userlists
  blocky-redis: 
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - $persist_data_home/blocky-redis-state:/data
  blocky-ui:
    image: ghcr.io/ivvija/blocky-ui
    restart: on-failure
    depends_on:
      - blocky
    environment:
      API_BASE_URL: http://blocky:4000/api
    env_file:  
      - secrets.enc.env  
    ports:
      - "3000:3000/tcp"
