services:
  mixpost:
      image: inovector/mixpost:latest
      env_file:
          - .env
      labels:
        - traefik.enable=true
        - traefik.http.routers.mixpost.rule=Host(`${APP_DOMAIN}`)
        - traefik.http.routers.mixpost.tls=true
        - traefik.http.routers.mixpost.entrypoints=web,websecure
        - traefik.http.routers.mixpost.tls.certresolver=mytlschallenge
        - traefik.http.middlewares.mixpost.headers.SSLRedirect=true
        - traefik.http.middlewares.mixpost.headers.STSSeconds=315360000
        - traefik.http.middlewares.mixpost.headers.browserXSSFilter=true
        - traefik.http.middlewares.mixpost.headers.contentTypeNosniff=true
        - traefik.http.middlewares.mixpost.headers.forceSTSHeader=true
        - traefik.http.middlewares.mixpost.headers.SSLHost=`${APP_DOMAIN}`
        - traefik.http.middlewares.mixpost.headers.STSIncludeSubdomains=true
        - traefik.http.middlewares.mixpost.headers.STSPreload=true
        - traefik.http.routers.mixpost.middlewares=mixpost@docker
      volumes:
          - $persist_data_home/mixpost/app:/var/www/html/storage/app
          - $persist_data_home/mixpost/logs:/var/www/html/storage/logs
      depends_on:
          - mysql
          - redis 
      restart: unless-stopped
      networks:
        - internal
        - traefik_backbone
  mysql:
      networks:
        - internal
      image: 'mysql/mysql-server:8.0'
      environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
      volumes:
          - persist_data_home/db:/var/lib/mysql
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p ${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
      restart: unless-stopped
  redis:
      image: 'redis:latest'
      command: redis-server --appendonly yes --replica-read-only no
      volumes:
          - $persist_data_home/redis:/data'
      healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          retries: 3
          timeout: 5s
      restart: unless-stopped  
      networks:
        - internal

networks:
  internal:
    name: web-prod-mixpost_Internal
    driver: bridge
    attachable: true
  traefik_backbone:
    # For external containers.
    name: traefik_backbone
    external: true