
services:
  traefik:
    image: "traefik:v3.5.3"
    command:
      #- "--log.level=DEBUG"
      - "-tracing=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entryPoints.p2p.address=:50300"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--providers.docker.network=traefik_backbone"
      - "--certificatesresolvers.httpsResolve.acme.httpchallenge=true"
      - "--certificatesresolvers.httpsResolve.acme.httpchallenge.entrypoint=web"
      - "--accesslog=true"
      - "--accesslog.format=json"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.httpsResolve.acme.email=rdean@stickpile.net"
      - "--certificatesresolvers.httpsResolve.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.directory=/rules"
      - "--log.level=INFO"
      - "--log.format=json"
    ports:
      - "80:80"
      - "443:443"
      - "50300:50300"
      - "8080:8080"
    volumes:
      - traefik_letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./rules:/rules
    restart: unless-stopped
    networks:
      - traefik_backbone
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`npm.stickpile.net`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=httpsResolve"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.middlewares=middlewares-authentik@file"
    # healthcheck:
    #   test: ["CMD", "traefik", "healthcheck", "--ping"]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 5s

volumes:
  traefik_letsencrypt:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${nfs_addr}"
      device: ":${nfs_appdata_share}/traefik/letsencrypt"

networks:
  traefik_backbone:
    name: traefik_backbone
    external: true
