name: affine
services:
  affine:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_server
    ports:
      - '${PORT:-3010}:3010'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.affine.rule=Host(`affine.stickpile.net`)"
      - "traefik.http.routers.affine.entrypoints=websecure"
      - "traefik.http.routers.affine.tls.certresolver=httpsResolve"
      - "traefik.http.services.affine.loadbalancer.server.port=3010"
      #- "traefik.http.routers.affine.middlewares=middlewares-authentik@file"
    volumes:
      # custom configurations
      - ${persist_data_home}/upload:/root/.affine/storage
      - ${persist_data_home}/config:/root/.affine/config
    env_file:  
      - secrets.enc.env  
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://$DB_USERNAME:$DB_PASSWORD@postgres:5432/$DB_DATABASE:-affine
      - AFFINE_INDEXER_ENABLED=false
    restart: unless-stopped
    networks:
      internal:
      traefik_backbone:

  affine_migration:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_migration_job
    volumes:
      # custom configurations
      - ${persist_data_home}/upload:/root/.affine/storage
      - ${persist_data_home}/config:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    env_file:  
      - secrets.enc.env  
    networks:
      internal:
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://$DB_USERNAME:$DB_PASSWORD@postgres:5432/$DB_DATABASE:-affine}
      - AFFINE_INDEXER_ENABLED=false

  redis:
    image: redis
    container_name: affine_redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      internal:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: affine_postgres
    volumes:
      - ${persist_data_home}/postgres}:/var/lib/postgresql/data
    env_file:  
      - secrets.enc.env  
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE:-affine
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # you better set a password for you database
      # or you may add 'POSTGRES_HOST_AUTH_METHOD=trust' to ignore postgres security policy
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      internal:
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', "${DB_USERNAME}", '-d', "${DB_DATABASE:-affine}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
networks:
  internal:
    name: web-prod-affine_Internal
    driver: overlay
    attachable: true
  traefik_backbone: # For external containers.
    name: traefik_backbone
    external: true
